language: csharp
dist: trusty
sudo: required
services: 
 - postgresql
before_script:
  - psql -c 'create database JsonApiDotNetCoreExample;' -U postgres
mono: none
dotnet: 1.0.0-preview2-1-003177
script:
  - ./build.sh