blank_issues_enabled: true
contact_links:
- name: Documentation
  url: https://www.jsonapi.net/usage/resources/index.html
  about: Read our comprehensive documentation.
- name: Sponsor JsonApiDotNetCore
  url: https://github.com/sponsors/json-api-dotnet
  about: Help the continued development.
- name: Ask on GitHub Discussions
  url: https://github.com/json-api-dotnet/JsonApiDotNetCore/discussions
  about: Get in touch with the whole community.
- name: Ask on Stack Overflow
  url: https://stackoverflow.com/questions/tagged/json-api
  about: The best place for asking general-purpose questions.
